ci: configuring test run report

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -31,4 +31,12 @@ jobs:
         run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
 
       - name: Run tests
-        run: npm test
+        run: npm run ci:test
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Test run report            # Name of the check run which will be created
+          path: reports/test-results.json    # Path to test results
+          reporter: mocha-json      # Format of test results
